import {
  IconCalendarWeek,
  IconCircle,
  IconLabel,
  IconRectangle,
  IconSquare,
  IconTypography,
} from "@tabler/icons-react";
import { ComboBoxIcon } from "../../components/icons/ComboBoxIcon";

export const FORM_ELEMENTS = [
  {
    id: "c0298038-8f88-4e2e-9deb-8b3e5021aeab",
    type: "text",
    icon: IconRectangle,
    label: "Text Field",
    config: {
      name: "",
      label: "Text Field",
      placeholder: "Enter text",
      value: "",
      required: false,
      style: {},
      className: "",
      disabled: false,
    },
  },
  {
    id: "f77add08-c1d0-44d8-a8a0-641bc4a666d4",
    type: "number",
    icon: IconRectangle,
    label: "Number Input",
    config: {
      name: "",
      label: "Number Input",
      placeholder: "Enter number",
      value: null,
      required: false,
      style: {},
      className: "",
      disabled: false,
    },
  },
  {
    id: "140ade69-f689-4679-99df-30e2a95fe4d6",
    type: "combo-box",
    icon: ComboBoxIcon,
    label: "Combo Box / Dropdown",
    config: {
      name: "",
      label: "Dropdown",
      options: [
        { label: "Option 1", value: "option_1" },
        { label: "Option 2", value: "option_2" },
      ],
      defaultValue: "",
      required: false,
      className: "",
      style: {},
      disabled: false,
    },
  },
  {
    id: "a1c60dfd-a662-43e7-924c-aebd2f74f25e",
    type: "number-combo-box",
    icon: ComboBoxIcon,
    label: "Number Combo Box",
    config: {
      name: "",
      label: "Number Dropdown",
      options: [
        { label: "One", value: "1" },
        { label: "Two", value: "2" },
        { label: "Three", value: "3" },
      ],
      defaultValue: "",
      required: false,
      className: "",
      style: {},
      disabled: false,
    },
  },
  {
    id: "df3e9e4a-b51a-46c6-8098-3615f95a0fb7",
    type: "radio",
    icon: IconCircle,
    label: "Radio Button",
    config: {
      name: "",
      label: "Choose an option",
      options: [
        { label: "Option A", value: "A" },
        { label: "Option B", value: "B" },
      ],
      value: "",
      required: false,
      className: "",
      style: {},
      inline: false,
      disabled: false,
    },
  },
  {
    id: "5940ff47-170c-4286-bb09-75a30b933655",
    type: "checkbox",
    icon: IconSquare,
    label: "Checkbox",
    config: {
      name: "",
      label: "Check options",
      options: [
        { label: "Option 1", value: "1" },
        { label: "Option 2", value: "2" },
      ],
      checked: [],
      required: false,
      className: "",
      style: {},
      disabled: false,
    },
  },
  {
    id: "72db6396-be0e-48fa-87ac-85041fcbe071",
    type: "date-picker",
    icon: IconCalendarWeek,
    label: "Datepicker",
    config: {
      name: "",
      label: "Pick a date",
      value: "",
      min: "",
      max: "",
      required: false,
      className: "",
      style: {},
      disabled: false,
    },
  },
  {
    id: "62fd1409-50ca-498a-82eb-1810efb97f02",
    type: "label",
    icon: IconLabel,
    label: "Label",
    config: {
      text: "Static Label",
      className: "",
      style: {},
    },
  },
  {
    id: "c6728b41-0d0e-4eb5-ba68-4070237f3700",
    type: "textarea",
    icon: IconTypography,
    label: "Textarea",
    config: {
      name: "",
      label: "Textarea",
      placeholder: "Enter long text",
      rows: 4,
      value: "",
      required: false,
      className: "",
      style: {},
      disabled: false,
    },
  },
];
